# Generated by Django 4.2 on 2023-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0002_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='OnlineShop.size'),
        ),
    ]
