# Generated by Django 4.2 on 2023-04-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0005_rename_category_category_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
