# Generated by Django 4.2 on 2023-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0008_color_product_quantity_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='size',
            field=models.CharField(max_length=64),
        ),
    ]
