# Generated by Django 4.2 on 2023-04-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0016_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
