# Generated by Django 4.2 on 2023-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0022_product_quantity_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_prod',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
