# Generated by Django 4.2 on 2023-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0023_order_quantity_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_prod',
            field=models.IntegerField(null=True),
        ),
    ]
