# Generated by Django 4.2 on 2023-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0025_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_create',
            field=models.CharField(max_length=64),
        ),
    ]
