# Generated by Django 4.2 on 2023-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0026_alter_comment_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
