# Generated by Django 4.2 on 2023-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0028_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_p',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
