# Generated by Django 4.2 on 2023-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0029_comment_review_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo'),
        ),
    ]
