# Generated by Django 4.2 on 2023-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0030_category_model_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_brands',
            name='slug',
            field=models.SlugField(default='scat', unique=True),
        ),
        migrations.AddField(
            model_name='category_for',
            name='slug',
            field=models.SlugField(default='cat', unique=True),
        ),
        migrations.AddField(
            model_name='category_model',
            name='slug',
            field=models.SlugField(default='xcat', unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='prod', unique=True),
        ),
        migrations.AddField(
            model_name='sex',
            name='slug',
            field=models.SlugField(default='sex', unique=True),
        ),
    ]
