# Generated by Django 4.2 on 2023-07-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0031_category_brands_slug_category_for_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_brands',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category_for',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category_model',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sex',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
